### PR TITLE
bugfix agent vqueue & refactor tools/deps

### PR DESCRIPTION
**Pull request by kpango**
Signed-off-by: kpango <kpango@vdaas.org>

### Description:

1. bugfix agent vqueue cache deletion logic
2. small changes to make command
    - fix sysctl params before k3d deployment (workaround for new linux kernel)
    - remove traefik from k3d deployment and add contour for IngressControler
    - use contour operator for kind deployment instead of raw contour deploy
    - patch metrics server to insecure for dev environment deploy k3d and kind works with it
    - change default e2e target to lb gateway from meta gateway
    - change default charts's dev.yaml deployment configuration's dimension to 784 (suitable for fashion-mnist dataset)
3. refactor small things

### Environment:

- Go Version: 1.16.4
- Docker Version: 19.03.8
- Kubernetes Version: 1.18.2
- NGT Version: 1.12.3

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [x] Refactoring [type/refactoring]
- [x] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by hlts2 — APPROVED** [review]
Thank you.
LGTM

**Review by kevindiu — APPROVED** [review]
LGTM

**Comment by kevindiu** [comment]
should we update patch version due to the fix?

**Comment by kpango** [comment]
I think so I'll check other PR that we can include next release.

**Pull request merged**
