### PR TITLE
Feature/drawio

### PR DESCRIPTION
**Pull request by taisuou**
### Description:
added assets for documentation of vald

1.separated overflow image into blocks and parts.
sc１
sc２

2.added scratchpad. you can copy and paste  blocks and parts.
sc3

### Environment:

- Go Version: 1.14.3
- Docker Version: 19.03.8
- Kubernetes Version: 1.18.2
- NGT Version: 1.11.5

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by vankichi** [comment]
@taisuou 
Could you please trim `space` from file name?

**Comment by kpango** [comment]
@vankichi I think is not necessary. We already use space naming delimiter, like https://github.com/vdaas/vald/blob/master/design/Vald%20Architecture%20Overview.drawio

**Comment by kpango** [comment]
is it important your use-case?

**Comment by vankichi** [comment]
If these files seem just template file, I don't mind too.
But, if we set these files as link at any pages in WebSite, it will not work well in WebSite.
The situation that we will set won't occur, I agree with you.

**Comment by kpango** [comment]
this file never read from the website because we should export them into SVG or PNG or webP.
we should care about naming then.

**Comment by vankichi** [comment]
Oh, I misundestand.
OK! NP!

**Comment by taisuou** [comment]
Sorry for late reaction....

**Pull request merged**
