### PR TITLE
[Bugfix] remove sudo from kubectl/install make command and small refactor around os/arch

### PR DESCRIPTION
**Pull request by kpango**
### Description:
Fixed CI Container build failure due to use of sudo in kubectl/install in the Makefile.
And refactored redundant OS/Arch switches.

### Versions:

- Go Version: 1.20.4
- Docker Version: 20.10.8
- Kubernetes Version: 1.27.1
- NGT Version: 2.0.11

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/main/CONTRIBUTING.md) document and completed [our CLA agreement](https://cla-assistant.io/vdaas/vald).
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?

### CODE REVIEW

**Review by vankichi — APPROVED** [review]

**Review by ykadowak — APPROVED** [review]
Thanks for the catch. Didn't realize it was failing.

I think we should stop `DeepSource: Test coverage` for now so that we realize some tests are actually failing.

**Comment by kpango** [comment]
To disabling the DeepSource-TestCoverage, we have to 
 edit https://github.com/vdaas/vald/blob/main/.deepsource.toml#L70.
Is it okay to separate it from this PR?

**Comment by ykadowak** [comment]
> To disabling the DeepSource-TestCoverage, we have to edit https://github.com/vdaas/vald/blob/main/.deepsource.toml#L70. Is it okay to separate it from this PR?

👍

**Comment by kpango** [comment]
@ykadowak https://github.com/vdaas/vald/pull/2038

**Pull request merged**
