### PR TITLE
add the missing go.sum

### PR DESCRIPTION
**Pull request by liusy182**
### Description:

Add the missing `go.sum`. Without that, the [get started](https://github.com/vdaas/vald/blob/master/docs/tutorial/get-started.md) tutorial did not work

### How Has This Been Tested?:

Tested locally by following the remaining steps in the get started guide.

### Environment:

- Go Version: 1.17.5
- Docker Version: 20.10.11
- Kubernetes Version: v1.21.4
- NGT Version: 1.13.8

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [x] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by vankichi — APPROVED** [review]
Thanks for  contributing :)

**Review by kpango — APPROVED** [review]
LGTM 👍 

Thank you

**Comment by vankichi** [comment]
@all-contributors please add @liusy182  for accessibility

**Comment by vankichi** [comment]
@all-contributors please add @liusy182 for example

**Pull request merged**
