### PR TITLE
Refactor E2E tests: split operations into a new package

### PR DESCRIPTION
**Pull request by rinx**
Signed-off-by: Rintaro Okamura <rintaro.okamura@gmail.com>

### Description:

In this PR, these changes are included.
- Add new packages for E2E testing:
	- tests/e2e/operations ... includes each opearations like Insert, Search, Update, ...
	- tests/e2e/kubernetes ... kubernetes related utilities like client, port forward, ...
	- tests/e2e/hdf5 ... hdf5 utilities
- using new packages, the existing E2E tests are refactored.

### Related Issue:

Wait for #1224 because it fixes `RequestId` in Search results.

### How Has This Been Tested?:

on CI

### Environment:

- Go Version: 1.16
- Docker Version: 19.03.8
- Kubernetes Version: 1.18.2
- NGT Version: 1.12.3

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [X] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [X] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [X] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [X] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by kpango — APPROVED** [review]
LGTM. Thank you for great job !!!

There are four points that I noticed.
1. the hdf5 package seems reusable with hack/e2e, so maybe we should consider moving it under internal or hack.
2. Since hdf5.Dataset and operation.Dataset have the same fields, you may want to use one of the types or use type Alias. 3.
3. consider adding Stream type and Multi type Operations in the future for CRUD testing.
4. Regarding the order of CRUD processing, Remove is called after Update, but since Vald is related to Update=(Remove+Insert), I think it would be better to test Remove -> Update in that order. Also, after Update, it would be nice to be able to confirm that the update was done using SearchByID or GetObject.

However, this PR is too large to achieve all these things, so I'll merge this PR and could you please consider about adding these things to the backlog?

**Comment by rinx** [comment]
@kpango Thanks for reviewing.

> 3. consider adding Stream type and Multi type Operations in the future for CRUD testing.

Stream APIs are already used. We should add tests for multiXXX APIs in the future.
I'm going to note in the task board the other points you mentioned.

**Comment by kpango** [comment]
@rinx seems good, would you mind if I merge this PR?

**Comment by rinx** [comment]
ok!

**Pull request merged**
