### PR TITLE
Refactor internal package doc.go

### PR DESCRIPTION
**Pull request by kevindiu**
### Description:
Change the package document to `doc.go` and remove the redundant package doc from the files.

### Related Issue:
https://github.com/vdaas/vald/issues/315

### Environment:

- Golang Version: 1.14
- Docker Version: 19.03.5
- Kubernetes Version: 1.17.3
- NGT Version: 1.9.1

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [x] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [x] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [x] I have added tests and benchmarks to cover my changes.
- [x] I have ensured all new and existing tests passed.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kpango** [comment]
I don't think this PR is effective.
Why did you remove the package comment from the existing code and add doc.go with the same comment?
Regarding the timing of adding doc.go, it is better to add detailed comments when adding the test code.

I recommend close this PR because all CI has failed. @vankichi What do you think?

**Comment by vankichi** [comment]
At first, I could not consider how this change is effective until you review.
We should talk about #315 more carefully and more deeply.

> Regarding the timing of adding doc.go, it is better to add detailed comments when adding the test code.
>  
> I recommend close this PR because all CI has failed. @vankichi What do you think?

I agree with you.
I want to sure that adding `doc.go` when adding the test code means not adding `doc.go` to PR#327, but adding `doc.go` per each adding/refactoring each test code.
How is it? @kpango

**Comment by kpango** [comment]
That's right, and I think that way is better.

**Pull request closed without merging**
