### PR TITLE
Update dataflow images

### PR DESCRIPTION
**Pull request by taisuou**
### Description:
update Insert flow
https://vald.vdaas.org/docs/overview/data-flow/

I would like to adjust search_flow, delete_flow, update_flow, and upsert_flow later, including their composition like insert_flow.

Currently, only the tone is adjusted to look good when the insert_flow is updated.
Please review the four attached images from just a layout issue.

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [x ] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### CODE REVIEW

**Comment by taisuou** [comment]
I made insert flow map vertically.Please check

スクリーンショット 2022-02-24 19 33
 .

**Comment by taisuou** [comment]
Edit the dataflow.io file tab by tab.
insert_flow, search_flow, delete_flow, update_flow, upsert_flow
exported as svg and png respectively.

For search_flow, delete_flow, update_flow, and upsert_flow, see
Only the tone and layout have been changed without altering the current configuration.
The user icons have been repositioned to the top, as the horizontal layout is difficult to see on a smartphone device


upsert_flow
update_flow
delete_flow
search_flow

**Comment by taisuou** [comment]
I would like to adjust search_flow, delete_flow, update_flow, and upsert_flow later, including their composition like insert_flow.

Currently, only the tone is adjusted to look good when the insert_flow is updated.
Please review the four attached images from just a layout issue.

**Comment by vankichi** [comment]
@taisuou 
current `data-flow` document uses `*_v2.svg`.
https://github.com/vdaas/vald/blob/master/docs/overview/data-flow.md

could you change image files whose names are `*_v2.svg`?
And, you do not have to delete image files that you did not change, please revert from this PR.

**Review by vankichi — APPROVED** [review]

**Review by vankichi — COMMENTED** [review]
please remove [design/Vald Architecture Basic.drawio](https://github.com/vdaas/vald/pull/1572/files#diff-add38a2b987a8844e870ceb31bea1e0d535ad5cf6dade270ae6828d32d4c526e).
Or, let me know why this file is needed.

**Review by kpango — APPROVED** [review]
LGTM

**Review by kpango — APPROVED** [review]
LGTM

**Review by vankichi — APPROVED** [review]

**Pull request merged**
