### PR TITLE
[minor] Release Vald v1.1.0

### PR DESCRIPTION
**Pull request by kpango**
#### Feature
- add correct grpc status and error handling (#1224)
- Add Cloud Storage mode of Agent Sidecar. (#519)
- Add general info metrics package / Add NGT info metrics (#1195)
- improve internal/info implementation (#1177)
- Add saving flag to index.info payload (#1200)
- Fix mysql and cassandra schema definitions in initialize jobs (#1186)
- Remove values-xxx.yaml from Helm packages (#1107)
- Feature/internal net/use netaddr (#1154)
- Add Nop Logger for empty logger message (#1158)
- Remove arm64 build of filter-ingress-tf (#1153)
- add tensorflow filter (#951)
- Add OpenAPIv3 schema to CRDs (#1068)
- PR for review all logging statements (#1052)
 
#### Bugfix
- bugfix gateway search result merging process (#1238)
- remove nil check in Error() method in internal/errors (#1185)
- Bug fix of parallel test and goleak (#1231)
- :rotating_light: Fix linting errors (#1179)
- Fix mutex deadlock when calling error occurred (#1225)
- fix nil pointer panic when err is nil in Is() (#1216)
- Fix typo & missed schema definition (#1156)
- :lock: Fix validation about zip slip (#1150)
- :lock: Fix security issue: Add validation about path of extracted file (#1145)
- fix: nil pointer bug when config is nil and refactor variable name (#1139)
- :bug: Fix gateway service selectors in Helm chart (#1109)
- Bugfix correct error handling for agent apis (#1144)

#### Document
- separate tutorials into each document and add images (#1230)
- Update Tutotial/Get-Started (#1203)
- Update unit-test-guideline.md (#1213)
- create docs/user-guides/sdks (#1182)
- Fix typo in README. (#1163)

#### CI/CD
- Upgrade to GitHub-native Dependabot (#1211)
- Use kubectl create/replace for upgrading CRDs (#1199)
- :wrench: Fix scylla deploy task (#1159)

#### Test Code
- Add config agent core ngt test (#1219)
- implement pkg/agent/core/ngt/router test & refactor router implementation (#1214)
- Implement pkg/agent/core/ngt/handler/grpc/option test (#1215)
- refactor config error handling (#1190)
- Implement pkg/agent/core/ngt/router/option test (#1206)
- Implement safety bench code (#1171)
- create internal/config/redis test (#1147)
- Implement internal/config/transport test (#1172)
- Add internal/config/sidecar test (#1173)
- Add benchmark for internal/timeutil/time.go (#1086)
- Add internal/config/observability unit test (#1155)
- Add test for internal/config/mysql (#1151)
- create internal/config/cassandra test (#1117) 
- create test for internal/config/server (#1175)
- Add internal/config/lb test (#1134)
- create internal/config/net test (#1140)
- :white_check_mark: create internal/config/meta test (#1133)
- Add internal/config/index test (#1129)
- :white_check_mark: create internal/config/backup test (#1132)
- delete internal/config/debug file (#1124)
- create internal/config/grpc test (#1130)
- Add internal/config/discoverer test (#1122)
- Add internal/config/filter.go test (#1125)
- create internal/config/gateway test (#1128)
- Implement internal/info/info.go benchmark (#1093)
- Add internal/config/client.go test (#1121)
- Implement internal/timeutil/location/loc.go benchmark test (#1091)
- :white_check_mark: remove unused variable from mysql test (#1120)
- feat: add blob test and comment (#1114)
- create bench code for internal/rand (#1089)
- Add test internal/config/compress.go (#1097)
- create internal/config/backoff test (#1104)
- change params for passing test of internal/backoff (#1108)
- remove unnecessary tests and update test (#1061)
- add internal backoff test (#1085)
- Add internal/core/algorithm/ngt/util.go test (#1066)
- Fix hack/tools/metrics failed builds (#1094)
- make timeouts for e2e and chaos tests longer (#1092)

#### Dependencies
- update go version to 1.16.4 (#1239)
- :arrow_up: Upgrade helm, valdcli, kubelinter and osdk (#1181)
- update codecov version for vulnerability (#1207)

#### Others
- update go modules (#1242)
- [ImgBot] Optimize images (#1241)
- Update license headers / Format codes (#1212)
- remove ngt version in filter-ingress-tensorflow (#1157)
- remove license from bot config json (#1164)
- improve internal/timeutil/location implementation (#1176)

### CODE REVIEW

**Comment by kpango** [comment]
@vdaas/core @vdaas/sre @vdaas/set can you please review it?

**Comment by kevindiu** [comment]
Updated formatting.
And I think item should be in `Other` column?
improve internal/timeutil/location implementation (#1176)

**Comment by rinx** [comment]
formatted.

**Comment by vankichi** [comment]
which one should we use uppercase or lowercase for each change?

**Comment by kpango** [comment]
I just generate it by git command I don't care about case.

**Comment by kpango** [comment]
@kevindiu resolved.

**Comment by kevindiu** [comment]
LGTM

**Pull request merged**
