### PR TITLE
add line trace logging when log mode is glg and level is debug

### PR DESCRIPTION
**Pull request by kpango**
Signed-off-by: kpango <kpango@vdaas.org>

### Description:
The glg update version has added LineTrace to the log output, and Vald is going to enable this feature only in DEBUG mode to improve the debugging efficiency.

```
2021-07-18 18:22:17     [INFO]: (https://go.uber.org/automaxprocs/blob/v1.4.0/maxprocs/maxprocs.go#L47):        maxprocs: Leaving GOMAXPROCS=16: CPU quota undefined
2021-07-18 18:22:17     [DEBG]: (https://github.com/vdaas/vald/blob/master/pkg/agent/core/ngt/service/ngt.go#L182):     vald agent starts with in-memory mode
2021-07-18 18:22:17     [DEBG]: (https://github.com/vdaas/vald/blob/master/internal/core/algorithm/ngt/ngt.go#L233):    failed to setup option :        github.com/vdaas/vald/internal/core/algorithm/ngt.WithIndexPath.func1: ignored option, name: indexPath
2021-07-18 18:22:17     [WARN]: (https://github.com/vdaas/vald/blob/master/pkg/agent/core/ngt/service/vqueue/queue.go#L94):     failed to setup option :        github.com/vdaas/vald/pkg/agent/core/ngt/service/vqueue.WithInsertBufferSize.func1: invalid option, name: insertBufferSize, val: 0
2021-07-18 18:22:17     [WARN]: (https://github.com/vdaas/vald/blob/master/pkg/agent/core/ngt/service/vqueue/queue.go#L94):     failed to setup option :        github.com/vdaas/vald/pkg/agent/core/ngt/service/vqueue.WithDeleteBufferSize.func1: invalid option, name: deleteBufferSize, val: 0
2021-07-18 18:22:17     [WARN]: (https://github.com/vdaas/vald/blob/master/pkg/agent/core/ngt/service/vqueue/queue.go#L94):     failed to setup option :        github.com/vdaas/vald/pkg/agent/core/ngt/service/vqueue.WithInsertBufferPoolSize.func1: invalid option, name: insertBufferPoolSize, val: 0
2021-07-18 18:22:17     [WARN]: (https://github.com/vdaas/vald/blob/master/pkg/agent/core/ngt/service/vqueue/queue.go#L94):     failed to setup option :        github.com/vdaas/vald/pkg/agent/core/ngt/service/vqueue.WithDeleteBufferPoolSize.func1: invalid option, name: deleteBufferPoolSize, val: 0
2021-07-18 18:22:17     [INFO]: (https://github.com/vdaas/vald/blob/master/internal/runner/runner.go#L134):     service agent ngt(version: v0.0.0)starting...
2021-07-18 18:22:17     [INFO]: (https://github.com/vdaas/vald/blob/master/internal/runner/runner.go#L145):     executing daemon pre-start function
2021-07-18 18:22:17     [INFO]: (https://github.com/vdaas/vald/blob/master/internal/runner/runner.go#L151):     executing daemon start function
2021-07-18 18:22:17     [INFO]: (https://github.com/vdaas/vald/blob/master/internal/servers/server/server.go#L247):     server grpc executing preStartFunc
2021-07-18 18:22:17     [DEBG]: (https://github.com/vdaas/vald/blob/master/internal/net/control/control.go#L95):        controlling socket for tcp6://0.0.0.0:8081, config &control.control{reusePort:false, reuseAddr:false, tcpFastOpen:false, tcpNoDelay:false, tcpCork:false, tcpQuickAck:false, tcpDeferAccept:false, ipTransparent:false, ipRecoverDestinationAddr:false, keepAlive:0}
2021-07-18 18:22:17     [DEBG]: (https://github.com/vdaas/vald/blob/master/internal/net/control/control.go#L95):        controlling socket for tcp6://0.0.0.0:3001, config &control.control{reusePort:false, reuseAddr:false, tcpFastOpen:false, tcpNoDelay:false, tcpCork:false, tcpQuickAck:false, tcpDeferAccept:false, ipTransparent:false, ipRecoverDestinationAddr:false, keepAlive:0}
2021-07-18 18:22:17     [INFO]: (https://github.com/vdaas/vald/blob/master/internal/servers/server/server.go#L293):     gRPC server grpc starting on tcp://[::]:8081
2021-07-18 18:22:17     [INFO]: (https://github.com/vdaas/vald/blob/master/internal/servers/server/server.go#L293):     REST server readiness starting on tcp://[::]:3001
```

### Environment:

- Go Version: 1.16.5
- Docker Version: 19.03.8
- Kubernetes Version: 1.18.2
- NGT Version: 1.12.3

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by hlts2 — APPROVED** [review]
thank you!
LGTM

**Review by hlts2 — APPROVED** [review]

**Comment by kevindiu** [comment]
can we remove the redundant string `https://github.com/vdaas/vald/blob/master/` from the log? I think currently the log message is too long

**Comment by kpango** [comment]
hmm... Isn't it useful to have a direct link to a line of code in the Github repository in this format?
glg also support short line trace, but it's shows only file-name and line

**Comment by kevindiu** [comment]
It is ok but I think it affects the readability of debug message 🤔 I think having this or not also ok for me

**Review by kevindiu — APPROVED** [review]

**Comment by kpango** [comment]
@kevindiu So, you mean you don't need trace info??

**Comment by kevindiu** [comment]
@kpango I mean that it is very useful but it affect the readability if we print out the full path of the file
My idea is that to take the balance, should we only print the `package_name/file_name:line` instead of including the github link.

**Comment by kpango** [comment]
@kevindiu how about this style?
```
2021-07-19 10:43:33     [INFO]: (go.uber.org/automaxprocs@v1.4.0/maxprocs/maxprocs.go:47):      maxprocs: Leaving GOMAXPROCS=16: CPU quota undefined
2021-07-19 10:43:33     [DEBG]: (github.com/vdaas/vald/pkg/agent/core/ngt/service/ngt.go:182):  vald agent starts with in-memory mode
2021-07-19 10:43:33     [DEBG]: (github.com/vdaas/vald/internal/core/algorithm/ngt/ngt.go:233): failed to setup option :        github.com/vdaas/vald/internal/core/algorithm/ngt.WithIndexPath.func1: ignored option, name: indexPath
2021-07-19 10:43:33     [WARN]: (github.com/vdaas/vald/pkg/agent/core/ngt/service/vqueue/queue.go:94):  failed to setup option :        github.com/vdaas/vald/pkg/agent/core/ngt/service/vqueue.WithInsertBufferSize.func1: invalid option, name: insertBufferSize, val: 0
2021-07-19 10:43:33     [WARN]: (github.com/vdaas/vald/pkg/agent/core/ngt/service/vqueue/queue.go:94):  failed to setup option :        github.com/vdaas/vald/pkg/agent/core/ngt/service/vqueue.WithDeleteBufferSize.func1: invalid option, name: deleteBufferSize, val: 0
2021-07-19 10:43:33     [WARN]: (github.com/vdaas/vald/pkg/agent/core/ngt/service/vqueue/queue.go:94):  failed to setup option :        github.com/vdaas/vald/pkg/agent/core/ngt/service/vqueue.WithInsertBufferPoolSize.func1: invalid option, name: insertBufferPoolSize, val: 0
2021-07-19 10:43:33     [WARN]: (github.com/vdaas/vald/pkg/agent/core/ngt/service/vqueue/queue.go:94):  failed to setup option :        github.com/vdaas/vald/pkg/agent/core/ngt/service/vqueue.WithDeleteBufferPoolSize.func1: invalid option, name: deleteBufferPoolSize, val: 0
2021-07-19 10:43:33     [INFO]: (github.com/vdaas/vald/internal/runner/runner.go:134):  service agent ngt(version: v0.0.0)starting...
2021-07-19 10:43:33     [INFO]: (github.com/vdaas/vald/internal/runner/runner.go:145):  executing daemon pre-start function
2021-07-19 10:43:33     [INFO]: (github.com/vdaas/vald/internal/runner/runner.go:151):  executing daemon start function
2021-07-19 10:43:33     [INFO]: (github.com/vdaas/vald/internal/servers/server/server.go:247):  server grpc executing preStartFunc
2021-07-19 10:43:33     [DEBG]: (github.com/vdaas/vald/internal/net/control/control.go:95):     controlling socket for tcp6://0.0.0.0:8081, config &control.control{reusePort:false, reuseAddr:false, tcpFastOpen:false, tcpNoDelay:false, tcpCork:false, tcpQuickAck:false, tcpDeferAccept:false, ipTransparent:false, ipRecoverDestinationAddr:false, keepA
live:0}
2021-07-19 10:43:33     [DEBG]: (github.com/vdaas/vald/internal/net/control/control.go:95):     controlling socket for tcp6://0.0.0.0:3001, config &control.control{reusePort:false, reuseAddr:false, tcpFastOpen:false, tcpNoDelay:false, tcpCork:false, tcpQuickAck:false, tcpDeferAccept:false, ipTransparent:false, ipRecoverDestinationAddr:false, keepA
live:0}
2021-07-19 10:43:33     [INFO]: (github.com/vdaas/vald/internal/servers/server/server.go:293):  REST server readiness starting on tcp://[::]:3001
2021-07-19 10:43:33     [INFO]: (github.com/vdaas/vald/internal/servers/server/server.go:293):  gRPC server grpc starting on tcp://[::]:8081

```

**Comment by kevindiu** [comment]
thank you! LGTM

**Comment by kpango** [comment]
@kevindiu @hlts2 thank you for reviewing. I'll merge this PR after CI passes.

**Pull request merged**
