### PR TITLE
fix invalid link

### PR DESCRIPTION
**Pull request by vankichi**
Signed-off-by: vankichi <kyukawa315@gmail.com>

### Description:

I fixed some links which occur as dead links at the official website:
  - change absURL about source code path (not another document link)
  - change godoc domain

### Environment:

- Go Version: 1.14.3
- Docker Version: 19.03.8
- Kubernetes Version: 1.18.2
- NGT Version: 1.11.5

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [x] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [x] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kevindiu** [comment]
can you also fix this?
https://github.com/vdaas/vald/pull/471/files#diff-c414e3e4151a3294cd86a33ca60eb228R7

**Comment by vankichi** [comment]
Sorry, I'm not sure what you mention.
Could you please tell me more detail?

**Comment by kevindiu** [comment]
Sorry seems github cannot jump to the code that I pointed :(
On line 7, the `Contribution guideline` is pointing to a symbolic link. Is it correct?
https://github.com/vdaas/vald/blob/d16b6637d89cc589cb97abff22b532f7f1162118/docs/contributing/coding-style.md

**Comment by vankichi** [comment]
arr ;(
Well, there is no problem what you mentioned.
The link under the `docs` dir will be overwritten when sync contents. 
You can confirm at [vdaas/web](https://github.com/vdaas/web/blob/master/Makefile#L162-L168).

**Pull request merged**
