### PR TITLE
[patch] Release v1.0.4 

### PR DESCRIPTION
**Pull request by rinx**
- Fix error handling of SearchByID API in lb gateway ([#1084](https://github.com/vdaas/vald/pull/1084))
- Update Agent dashboard ([#1069](https://github.com/vdaas/vald/pull/1069))
- Revise gRPC error statuses and details in meta (Redis/Cassandra) ([#1013](https://github.com/vdaas/vald/pull/1013))
- add remove sample code for tutorial ([#1053](https://github.com/vdaas/vald/pull/1053))
- add grpc reflection ([#1064](https://github.com/vdaas/vald/pull/1064))
- remove vcache for vald agent due to vcache delete timing control failure and time ordered concurrent vector queue called vqueue ([#1028](https://github.com/vdaas/vald/pull/1028))
- refactor discoverer client ([#1056](https://github.com/vdaas/vald/pull/1056))
- bugfix nil pointer no target discovered ([#1055](https://github.com/vdaas/vald/pull/1055))
- Upgrade Operator SDK version to v1.4.2 ([#1038](https://github.com/vdaas/vald/pull/1038))

### CODE REVIEW

**Comment by rinx** [comment]
the E2E Chaos tests passed.
https://github.com/vdaas/vald/runs/2127450527

the E2E deploy tests failed but it's known problem of Update APIs.
https://github.com/vdaas/vald/runs/2127450660

@kevindiu @vankichi @datelier @hlts2 Could you check if we can release or not?

**Review by kpango — APPROVED** [review]
LGTM

**Comment by kpango** [comment]
@rinx each features in this release were committed by @kpango  and @rinx I think it's okay to release v1.0.4

**Comment by rinx** [comment]
okay :+1:

**Comment by kpango** [comment]
@rinx thanks!
Congrats for v1.0.4

**Pull request merged**
