### PR TITLE
Add install scripts for kind, helm, and valdcli

### PR DESCRIPTION
**Pull request by rinx**
Signed-off-by: Rintaro Okamura <rintaro.okamura@gmail.com>

### Description:

I added install scripts for kind, helm and valdcli.
The install path could be specified using BINDIR argument like the followings:

```sh
$ make tools/install BINDIR=libs/bin  ## <- put kind, helm and valdcli into libs/bin dir
$ make kind/install BINDIR=~/local/bin
$ make helm/install
$ make valdcli/install
```

The default BINDIR=/usr/local/bin.

### Related Issue:

Nothing.

### How Has This Been Tested?:

Nothing.

### Environment:

- Golang Version: 1.13.6
- Docker Version: 19.03.5
- Kubernetes Version: 1.16.3
- NGT Version: 1.8.4

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [X] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [X] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [X] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensure all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kpango** [comment]
could you please add telepresense?

**Comment by rinx** [comment]
currently i couldn't complete to install telepresence into my local environment. (maybe missing dependencies)
so i'll send another PR for it.

**Comment by kpango** [comment]
hmm, here is my telepresence install script please check it
https://github.com/kpango/dotfiles/blob/master/dockers/k8s.Dockerfile#L81-L85
and dependencies are below
https://github.com/kpango/dotfiles/blob/master/dockers/k8s.Dockerfile#L15-L17

**Comment by rinx** [comment]
it is revealed that telepresence requires python3-venv package in Ubuntu-based environment.
Okay, i'll try to add telepresence installation script to this PR. :ok_hand:

**Comment by kpango** [comment]
LGTM
/approve

**Pull request merged**
