### PR TITLE
change test assets for new design api

### PR DESCRIPTION
**Pull request by kpango**
Signed-off-by: kpango <i.can.feel.gravity@gmail.com>

### Description:
 Use t.Parallel for improve test performance.
This PR is sub PR for #740 

### Environment:

- Go Version: 1.15.2
- Docker Version: 19.03.8
- Kubernetes Version: 1.18.2
- NGT Version: 1.12.1

### Types of changes:

- [ ] Bug fix [type/bug]
- [x] New feature [type/feature]
- [x] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [x] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by hlts2 — APPROVED** [review]
LGTM

**Comment by kevindiu** [comment]
my looking at this article, I think we may need some testing for this problem.
https://gist.github.com/posener/92a55c4cd441fc5e5e85f27bca008721

@hlts2 @vankichi what do you think?

**Comment by vankichi** [comment]
we should take care about https://github.com/vdaas/vald/pull/741#issuecomment-705527680
This article is a bit old, so we have to check with the latest Go.
And, also you can also see https://gist.github.com/posener/92a55c4cd441fc5e5e85f27bca008721#gistcomment-2697310
@kevindiu

**Comment by kpango** [comment]
@vankichi @kevindiu fixed

**Review by vankichi — APPROVED** [review]

**Pull request merged**
