### PR TITLE
Fixed a bug that could cause duplicate counts of working_memory_set_bytes

### PR DESCRIPTION
**Pull request by takuyaymd**
### Description:

- In the container_memory_working_set_bytes metric, 
Fixed a bug that could cause duplicate data to be summed if this metric was outputting the Pod's own data, not just the data for each container contained in the Pod.

- I used the `image` label value to distinguish between per-container data and other data.
### Versions:

- Go Version: 1.19.4
- Docker Version: 20.10.8
- Kubernetes Version: 1.22.0
- NGT Version: 1.14.8

### Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/main/CONTRIBUTING.md) document and completed [our CLA agreement](https://cla-assistant.io/vdaas/vald).
- [x] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?

### CODE REVIEW

**Comment by kpango** [comment]
Can you please sign CLA ?

**Comment by takuyaymd** [comment]
> Can you please sign CLA ?

Sorry, I screwed up setting up the author!

**Review by kpango — APPROVED** [review]
LGTM

**Comment by kpango** [comment]
@all-contributors please add @takuyaymd for bug, code

**Review by hlts2 — APPROVED** [review]
LGTM!

**Pull request merged**
