### PR TITLE
refactor(gateway): delete unused file

### PR DESCRIPTION
**Pull request by highpon**
### Description
The file `pkg/gateway/internal/location/location_test.go` exists but is not used.
This PR removes `pkg/gateway/internal/location/location_test.go`, which is not used.

### Versions

- Vald Version: v1.7.13
- Go Version: v1.23.1
- Rust Version: v1.81.0
- Docker Version: v27.2.1
- Kubernetes Version: v1.31.0
- Helm Version: v3.16.0
- NGT Version: v2.2.4
- Faiss Version: v1.8.0

### Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/main/CONTRIBUTING.md) document and completed [our CLA agreement](https://cla-assistant.io/vdaas/vald).
- [x] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?

## Summary by CodeRabbit

- **Chores**
	- Removed the `location_test.go` file, which contained licensing information and package declarations but no functional code or tests.

### CODE REVIEW

**Comment by kpango** [comment]
Thank you for your contribution.
It would be better to remove pkg/gateway/internal directory as well, which is never used for now.

**Comment by kpango** [comment]
@all-contributors please add @highpon for test

**Comment by highpon** [comment]
@kpango 
Thanks for the review!
I checked and the pkg/gateway/internal directory was also gone in the current commit!
https://github.com/highpon/vald/tree/refactoring/gateway/delete-unused-file/pkg/gateway

So it looks like I don't need to create a new commit!

**Comment by kpango** [comment]
Got it.

**Review by kpango — APPROVED** [review]

**Review by hlts2 — APPROVED** [review]
LGTM!

**Pull request merged**
