### PR TITLE
Two version deploy support

### PR DESCRIPTION
**Pull request by hlts2**
### Description:

In this PR, it includes a change to support 2 version deploy.
The workflow related to the 2 version deploy is as below.

- [semver-major-minor.yaml](https://github.com/vdaas/vald/blob/feature/ci/two-version-deploy-support/.github/workflows/semver-major-minor.yaml)
  - This workflow creates a release PR when there is a `major/minor` related commit.
- [semver-patch.yaml](https://github.com/vdaas/vald/blob/feature/ci/two-version-deploy-support/.github/workflows/semver-patch.yaml)
  - The workflow is to create a release PR when there is a commit related to `patch`.
- [_release-pr.yml](https://github.com/vdaas/vald/blob/feature/ci/two-version-deploy-support/.github/workflows/_release-pr.yml)
  - This is a reusable workflow. When this is called, update the charts, k8s, ...etc with the corresponding semantic version and create a release PR.
- [release.yml](https://github.com/vdaas/vald/blob/feature/ci/two-version-deploy-support/.github/workflows/release.yml)
  - This is the workflow for the actual release when the release PRs are merged.
- [backport.yml](https://github.com/vdaas/vald/blob/feature/ci/two-version-deploy-support/.github/workflows/backport.yml)
  - This is the workflow for backporting a feature: if a label like `actions/backport/main`, `actions/backport/release/v1.8` exists in the PR, vdaas-ci creates a new PR to another branch (`main`, `release/v1.8`) with squash merge commit.
- [determine-docker-image-tag/action.yaml](https://github.com/vdaas/vald/blob/feature/ci/two-version-deploy-support/.github/actions/determine-docker-image-tag/action.yaml)
  - The docker image tag is important in realizing the 2 version deploy. Since we have created actions to determine the docker tag in the previous [PR](https://github.com/vdaas/vald/pull/2141), the logic around the image tag is included here. We can get the proper docker image tag considering the current branch.
- [_detect-ci-container.yml](https://github.com/vdaas/vald/blob/feature/ci/two-version-deploy-support/.github/workflows/_detect-ci-container.yml)
  - This is a reusable workflow. This allows us to dynamically change the image tags of ci-container.

### Versions:

- Go Version: 1.21.0
- Docker Version: 20.10.8
- Kubernetes Version: v1.28.1
- NGT Version: 2.1.3

### Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/main/CONTRIBUTING.md) document and completed [our CLA agreement](https://cla-assistant.io/vdaas/vald).
- [x] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?

### CODE REVIEW

**Comment by vankichi** [comment]
@hlts2 Thanks.
Could you please show us the design of this workflow with details in the PR description? :smile:

**Review by datelier — DISMISSED** [review]

**Review by kpango — APPROVED** [review]
LGTM

**Review by kevindiu — DISMISSED** [review]

**Comment by ykadowak** [comment]
`pr.yml` should probably be something like `backport.yml`?

**Comment by hlts2** [comment]
@ykadowak Thank you for the suggestion! it looks good to me. I will change it.

**Review by ykadowak — DISMISSED** [review]

**Review by kpango — DISMISSED** [review]
LGTM

**Review by vankichi — DISMISSED** [review]
LGTM

**Review by kevindiu — DISMISSED** [review]

**Review by ykadowak — APPROVED** [review]

**Review by ykadowak — APPROVED** [review]

**Review by datelier — APPROVED** [review]

**Review by ykadowak — DISMISSED** [review]

**Review by vankichi — DISMISSED** [review]

**Review by kpango — APPROVED** [review]
LGTM

**Review by kmrmt — DISMISSED** [review]

**Comment by hlts2** [comment]
Thank you for your previous review 🙏
Sorry, I updated the license header and the approval disappeared....
There is no change to the logic.

**Review by vankichi — APPROVED** [review]

**Review by datelier — APPROVED** [review]

**Review by ykadowak — APPROVED** [review]

**Review by kpango — APPROVED** [review]

**Pull request merged**
