### PR TITLE
Feature/internal net/use netaddr

### PR DESCRIPTION
**Pull request by kpango**
### Description:
The problems with the net package were mentioned on tailscale's blog: https://tailscale.com/blog/netaddr-new-ip-type-for-go/
ParseIP, etc. in Vald as well, so I'm going to use this as long as it's not reflected in Go official.

#### [WARNING] **The diffs seems large because of the gofumport, but the only file to review in this PR is internal/net/net.go, so please review this file only.**
[internal/net/net.go](https://github.com/vdaas/vald/pull/1154/files#diff-e0420d9909f993cb94810e129226c6331a5fa740537ef5846bab1596a0c3b63f)

### Environment:

- Go Version: 1.16
- Docker Version: 19.03.8
- Kubernetes Version: 1.18.2
- NGT Version: 1.12.3

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [ ] Add documents [type/documentation]
- [x] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kpango** [comment]
The diffs seems large because of the gofumport, but the only file to review in this PR is internal/net/net.go, so please review this file only.
[internal/net/net.go](https://github.com/vdaas/vald/pull/1154/files#diff-e0420d9909f993cb94810e129226c6331a5fa740537ef5846bab1596a0c3b63f)

**Comment by rinx** [comment]
Seems good.
Please make it up-to-date and run e2e tests before merge.

**Comment by kpango** [comment]
seems E2E deploy test failed but it seems deadline error which caused by GithubActions server spec.
but E2E chaos passed I think this patch works, I'll merge this branch thank you for reviewing.

**Pull request merged**
