### PR TITLE
refactor index manager service add index service API to expose index informations

### PR DESCRIPTION
**Pull request by kpango**
### Description
The following modifications have been made to this PR.
- Refactoring of IndexManager
    - Integration of Index proto into Vald proto
    - IndexInfo, IndexDetail, and GetTimestamp APIs are now available outside of Index manager
- Automatic Dockerfile generation
    - https://github.com/vdaas/vald/blob/refactor/manager-index/small-refactor/hack/docker/gen/main.go
- Fixes to Typo
- Expose IndexDetail API
- Ingress Route optimization
    - Added pass-through to LB when using MirrorGateway or FilterGateway as specific API processing is not needed
- Add Formatter (crlfmt)
    - https://github.com/cockroachdb/crlfmt
- Detailing of internal info API
　- Add GoMaxProcs, CGOCall, GoroutineCount, RuntimeCPUCores

Translated with DeepL.com (free version)

### Versions

- Go Version: 1.22.5
- Rust Version: 1.77.2
- Docker Version: 20.10.8
- Kubernetes Version: v1.30.2
- NGT Version: 2.2.2

### Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/main/CONTRIBUTING.md) document and completed [our CLA agreement](https://cla-assistant.io/vdaas/vald).
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?

### CODE REVIEW

**Comment by kpango** [comment]
@coderabbitai please review

**Comment by kpango** [comment]
@coderabbitai summary

**Comment by kpango** [comment]
@coderabbitai full review

**Review by kmrmt — APPROVED** [review]

**Review by hlts2 — DISMISSED** [review]
LGTM!

**Review by hlts2 — DISMISSED** [review]
LGTM!!

**Review by datelier — APPROVED** [review]

**Review by hlts2 — DISMISSED** [review]
LGTM!

**Review by kmrmt — APPROVED** [review]

**Review by hlts2 — APPROVED** [review]
LGTM!

**Review by kmrmt — APPROVED** [review]

**Review by datelier — APPROVED** [review]

**Pull request merged**
