### PR TITLE
[patch] Release Vald v1.2.1

### PR DESCRIPTION
**Pull request by kpango**
- remove global errgroup from kvsdb goroutine limitation (#1398)
- add google grpc healthz & logger (#1394)
- fix e2e multi apis test code (#1397)
- :pencil: fix command in vald agent standalone on docker (#1393)
- add Makefile & Makefile.d to build kick rule (#1391)
- format codes (#1389)
- [proposal] add golines as vald default formatter (#1337)
- replace gogo protobuf to vt protobuf (#1378)
- refactor gateway request result location aggregation logic & use xxh3 for kvsdb hashing (#1376)
- Add E2E tests for multi-APIs (#1353)
- Add test for the function to get length of vqueue (#1382)
- remove unused path of format/yaml command (#1383)
- [Documentation] fix image filename (#1377)
- Vald moves to a vector search engine that enables more simple and high-speed retrieval. This is the first step of Simple-Vald. (#1365)
- Add e2e-profiling job (#1356)
- fix svg error on dataflow image (#1375)
- remove invalid gateway component reference from chart.NOTES (#1371)

### CODE REVIEW

**Comment by rinx** [comment]
I don't know but, is vtprotobuf compatible with gogoprotobuf? If it is not compatible, it should be a breaking change.

**Comment by kpango** [comment]
@rinx Thanks for comment.
The transition from gogo to vt was definitely a big task, and actually we have moved from go protobuf v1 to go protobuf v2 in terms of internal API compatibility, but from the user's point of view, the user serializer is still a protocolbuffer, and there is no Breaking Change in the User Interface. 
So, I'm planning to release this as a patch version.

**Comment by rinx** [comment]
ok, thanks

**Review by kevindiu — APPROVED** [review]
no problem with rebalancer

**Comment by kpango** [comment]
Release blocker
- https://github.com/vdaas/vald/pull/1397
- https://github.com/vdaas/vald/pull/1394

**Review by hlts2 — APPROVED** [review]

**Pull request merged**
