### PR TITLE
add reviewer guideline

### PR DESCRIPTION
**Pull request by kmrmt**
### Description

add guideline for reviewers

### Versions

- Go Version: 1.22.3
- Rust Version: 1.77.2
- Docker Version: 20.10.8
- Kubernetes Version: v1.30.0
- NGT Version: 2.2.1

### Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/main/CONTRIBUTING.md) document and completed [our CLA agreement](https://cla-assistant.io/vdaas/vald).
- [X] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?

## Summary by CodeRabbit

- **Documentation**
  - Added a comprehensive reviewer guideline for Pull Requests in the Vald project. This document covers preparation, review requests, approval conditions, reviewer responsibilities, communication methods, and effect measurement to optimize the review process and ensure quality control.

### CODE REVIEW

**Comment by kmrmt** [comment]
@coderabbitai review

**Comment by kmrmt** [comment]
https://github.com/coderabbitai review

**Comment by kmrmt** [comment]
@coderabbitai review

**Comment by kmrmt** [comment]
@coderabbitai review

**Review by datelier — APPROVED** [review]

**Review by kpango — APPROVED** [review]

**Pull request merged**
