### PR TITLE
add troubleshooting flow chart document

### PR DESCRIPTION
**Pull request by vankichi**
Signed-off-by: vankichi <kyukawa315@gmail.com>

### Description:

I have added the flow chart for troubleshooting and a new document file for it.

~~I wonder whether divide troubleshooting documents into `chart.md` and `troubleshooting.md` and this chart covers almost trouble for the Vald cluster.
Please feedback.~~

I have created the new document directory, `troubleshooting`.
The document tres is here:
|- :file_folder: troubleshooting
|            |- :memo: README : overview of this directory (the path will be /docs/troubleshooting/ on the web site)
|            |- :memo: Flow Chart : showing troubleshooting flow chart for the Vald cluster
|            |- :memo: Operation Troubleshooting : introducing troubleshooting for client operation

### Environment:

- Go Version: 1.18.2
- Docker Version: 20.10.8
- Kubernetes Version: 1.22.0
- NGT Version: 1.14.5

### Types of changes:

- [ ] Bug fix [type/bug]
- [ ] New feature [type/feature]
- [ ] Add tests [type/test]
- [ ] Security related changes [type/security]
- [x] Add documents [type/documentation]
- [ ] Refactoring [type/refactoring]
- [ ] Update dependencies [type/dependency]
- [ ] Update benchmarks and performances [type/bench]
- [ ] Update CI [type/ci]

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### Checklist:

- [ ] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/master/CONTRIBUTING.md) document.
- [ ] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?
- [ ] I have added tests and benchmarks to cover my changes.
- [ ] I have ensured all new and existing tests passed.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by kmrmt — CHANGES_REQUESTED** [review]
About troubleshooting_chart.svg, in my environment that is google chrome version 102.0.5005.61, Linux(Voyager Linux 22..04 LTS, kernel 5.15.0-33-generic) and google chrome version 102.0.5005.63 and Windows 11, the whole of command is not visible like below.

In Linux
```
$ kubectl get pod -o w
```

In Windows
```
$ kubectl get pod
```

**Review by kmrmt — DISMISSED** [review]

**Comment by kevindiu** [comment]
I am sorry that I want to confirm what content do you expect on `chat.md` and `trobleshooting.md`?

**Comment by kevindiu** [comment]
I think it may be better to use `End` instead of black circle point as I can't understand what it means.
Also do we need @taisuou to review this diagram after/during we review the content of the diagram?

**Comment by vankichi** [comment]
> I am sorry that I want to confirm what content do you expect on `chat.md` and `trobleshooting.md`?

I meant should we combine `chart.md` and `troubleshooting.mg` in one file or keep 2 files.
Please give me your thoughts.

**Comment by vankichi** [comment]
> I think it may be better to use `End` instead of black circle point as I can't understand what it means. Also do we need @taisuou to review the design after/during we review the content of the diagram?

The black circle means the end of the flow chart, and I think it is the general expression.
Nevertheless, do you think it should be changed?

IMO, it is not needed.
Anyway, we have to pass the review from all core contributors.

**Comment by kevindiu** [comment]
> The black circle means the end of the flow chart, and I think it is the general expression.

This is the first time I see this expression, however I couldn't find any example that represent the end of the flow chart as a black circle, do you have any reference for it?
I could only find the circle with the `End` wording is the similar expression from yours.

Ref: https://duckduckgo.com/?q=flowchart+end&atb=v314-1&iax=images&ia=images&iai=https%3A%2F%2Fcdn2.slidemodel.com%2Fwp-content%2Fuploads%2F6658-01-business-process-infographics-16x9-1.jpg

**Comment by kevindiu** [comment]
> I meant should we combine chart.md and troubleshooting.mg in one file or keep 2 files.
Please give me your thoughts.

I think we can combine them as I think splitting them cause harder to find the flow chart, what do you think?

**Comment by vankichi** [comment]
@kevindiu 
I have updated the flow chart and document.

**Comment by kevindiu** [comment]
Should we fix the following things?

- `vald` -> `Vald`
- `vald-helm operator is runnig?` -> `vald-helm-operator is running?` (typo on running and missing `-`)
- `k8s` -> `K8s`
- `Your CPU applies AVX2?` -> `Your CPU support AVX2?`
- `Docker image availeble` -> `Docker image available` (type)
- `Vald LB Gateway` -> `Vald-LB-Gateway`?

**Comment by kevindiu** [comment]
Sorry but can I confirm what is the meaning of `Deploy metrics-server Ref`?

**Comment by vankichi** [comment]
@kevindiu 
`Ref` has the link.
Deploy metrics-server\nRef is correct

**Comment by vankichi** [comment]
> Should we fix the following things?
> 
> * `vald` -> `Vald`

I'll fix

> * `vald-helm operator is runnig?` -> `vald-helm-operator is running?` (typo on running and missing `-`)

It may your mis-seeing.

> * `k8s` -> `K8s`

I'll fix

> * `Your CPU applies AVX2?` -> `Your CPU support AVX2?`
> * `Docker image availeble` -> `Docker image available` (type)

I'll fix

> * `Vald LB Gateway` -> `Vald-LB-Gateway`?

`Vald LB Gateway` is fine. It's not the container name.

**Comment by kevindiu** [comment]
Sorry again but I found 2 more typo on `runnig`.
- `Filter Gateway runnig`
- `Filter Component is runnig`

**Review by kmrmt — DISMISSED** [review]

**Review by kevindiu — DISMISSED** [review]
LGTM

**Review by kmrmt — APPROVED** [review]

**Review by hlts2 — APPROVED** [review]
LGTM!!

**Review by kpango — CHANGES_REQUESTED** [review]
I think we should describe about helm-operator upgrading.
user have to update thier CRDs.
it would be better to embed command or add links to the upgrade document

**Comment by vankichi** [comment]
> I think we should describe about helm-operator upgrading. user have to update thier CRDs. it would be better to embed command or add links to the upgrade document

I have embedded the upgrade document link at the `upgrate vald-helm-operator`.
I suppose `Github PR preview` page does not apply. You can verify on the page of the original file path.

**Review by kevindiu — APPROVED** [review]

**Review by kpango — APPROVED** [review]
LGTM

**Review by hlts2 — APPROVED** [review]
LGTM!

**Review by datelier — APPROVED** [review]

**Pull request merged**
