### PR TITLE
Create README for each docker image

### PR DESCRIPTION
**Pull request by vankichi**
### Description:

I have created README for each Docker image.
The purpose is to copy these documents to the `hub.docker` and makes a more user-friendly page for each Docker image.

### Versions:

- Go Version: 1.20.3
- Docker Version: 20.10.8
- Kubernetes Version: 1.22.0
- NGT Version: 2.0.9

### Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/vdaas/vald/blob/main/CONTRIBUTING.md) document and completed [our CLA agreement](https://cla-assistant.io/vdaas/vald).
- [x] I have checked open [Pull Requests](https://github.com/vdaas/vald/pulls) for the similar feature or fixes?

### Special notes for your reviewer:

All files have the `requirement` section for using each image.
However, I'm not sure about everything, please check out more carefully and review :pray:

### CODE REVIEW

**Comment by kpango** [comment]
Overall looks good.
It would be better to add environment or requirements eg.CPU, AVX, etc...

**Review by kpango — APPROVED** [review]

**Review by hlts2 — APPROVED** [review]
LGTM

**Review by kevindiu — APPROVED** [review]

**Review by ykadowak — APPROVED** [review]

**Review by datelier — DISMISSED** [review]

**Review by ykadowak — APPROVED** [review]

**Review by hlts2 — DISMISSED** [review]
LGTM

**Review by kpango — APPROVED** [review]
LGTM

**Review by datelier — DISMISSED** [review]

**Review by kevindiu — APPROVED** [review]

**Review by kpango — APPROVED** [review]
LGTM

**Review by hlts2 — APPROVED** [review]

**Review by kevindiu — APPROVED** [review]

**Pull request merged**
